### PR TITLE
Remove `create-react-app` development server

### PR DESCRIPTION
**Pull request by tulup-conner**
Finally, it's time. See #221 

https://flowbite-react.vercel.app

### CODE REVIEW

**Comment by tulup-conner** [comment]
Let's roll #165 #166 #167 into this also

**Comment by zoltanszogyenyi** [comment]
Hey @tulup-conner,

I've contributed by adding some custom container classes so that it looks nice and tidy. We still have a lot of work to do by adding the TOC and making sure that spaces are well constrained - we'll get there eventually!

Cheers,
Zoltan

**Comment by tulup-conner** [comment]
Im confused why your commits changed the order of so many class names

**Comment by zoltanszogyenyi** [comment]
@tulup-conner I'm pretty sure it's because of the Headwind plugin I had in VS code - I've removed it since I forgot I had on my iMac back at home.

Screenshot 2023-03-05 at 18 30 00

I believe we now use the official Prettier plugin from Tailwind CSS? Is this integrated when pushing code?

**Comment by rluders** [comment]
This PR feelings:
https://www.instagram.com/p/CougVrfDVVq/

**Comment by tulup-conner** [comment]
@rluders I have a bad history of doing that for which you can definitely put me on blast but this one is actually unavoidable lol

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

The docs redesign is based on this Figma file if anyone wants to contribute:

https://www.figma.com/file/9niSMwJTN8HU45pmY9xuil/Flowbite-react?type=design&node-id=1%3A231694&t=vfYrkIDkLYFi5b9C-1

I've already built a couple of sections for the homepage layout and the main docs looks pretty good, but there's still work to be done with the sidebar and some other functionalities.

Here's how it should look in the end:

Screenshot 2023-05-05 at 12 20 15

Cheers,
Zoltan

**Pull request merged**
