### PR TITLE
perf(component treeshaking): updated config and build files to treesh…

### PR DESCRIPTION
**Pull request by ddiasfront**
Each component can now OPTIONALLY be imported individually from the components path.

EXAMPLE:

```
import { Badge } from "flowbite-react/components/Badge";

function App() {
  return (
    <div className="w-10/12">
      <Badge>Test</Badge>
    </div>
  );
}
```

Components with old pattern:
```

import { Badge } from "flowbite-react";

function App() {
  return (
    <div className="w-10/12">
      <Badge>Test</Badge>
    </div>
  );
}
```

Will still work, but will still treeshake hell as well.

PS: This pr will not fix the themes treeshaking which seems to be more complex.

#1197

Keen to hear back from the maintainers.

FINAL BUILD RESULT with "/components":
Screenshot 2024-01-07 at 22 43 02

FINAL BUILD RESULT w/out "/components":
Screenshot 2024-01-07 at 23 37 51

### CODE REVIEW

**Comment by SutuSebastian** [comment]
Will be implemented in the next version of the monorepo -> next release

**Comment by toteto** [comment]
The approach is OK, think it solves partially the reported issue of #1197. 

> Will be implemented in the next version of the monorepo -> next release

@SutuSebastian is this fix you are mentioning part of 7.3? What version will the fix be in? Is there a PR of the fix you mentioned?

**Comment by SutuSebastian** [comment]
> The approach is OK, think it solves partially the reported issue of #1197. 
> 
> 
> 
> > Will be implemented in the next version of the monorepo -> next release
> 
> 
> 
> @SutuSebastian is this fix you are mentioning part of 7.3? What version will the fix be in? Is there a PR of the fix you mentioned?

There is a PR on it, its #1264, almost done.

**Comment by SutuSebastian** [comment]
Fixed in https://github.com/themesberg/flowbite-react/pull/1264

**Pull request closed without merging**
