### PR TITLE
Monorepo conversion (using `bun`)

### PR DESCRIPTION
**Pull request by SutuSebastian**
### Summary

Since there is a lot of confusion regarding which files belong to docs, and which belong to the UI library, as well as which files are simply for code quality and which not, we should have a split bringing separation of concerns that isolates each app/package into their own namespace, while still allowing the flexibility of re-usage of one another (eg: UI lib being used in docs namespace).

To achieve this, the answer is **monorepo**.

### Structure
- [x] apps
    - [x] storybook
    - [x] web
- [x] packages
    - [x] cli
    - [x] ui

### Stack

Task runner: `Bun`
Package manager: `Bun`
Lint: `ESLint`
Format: `Prettier`
Test: `Vitest`
Release: `Changesets`
Monorepo: `Bun`
Monorepo build system: `Turborepo`

### Changes

General:
- upgrade all packages to safe latest
- refactor github actions
- setup github actions using `bun`
- remove storybook github action (redo later if needed)
- formatter - switch from singleQuote to double
- re-do from the ground up: IDE, linting, formatting configs
- removed `cypress` (to be replaced with `playwright`)
- removed `codecov`
- split into multiple packages and apps [web(docs), ui(library), storybook, cli]

Docs:
- improve homepage speed
- fix homepage components section card hover on dark mode
- add new `CLI` page
- add new `Editor Setup` page
- add CLI command section to all integration guides
- refactor `Quickstart` page
- code preview
  - desktop/tablet/phone toggle buttons sizes
  - RTL toggle button
  - light/dark mode actually working in isolation (+ syncing with root on init and change if `mode` matches)
-  remix guide: add dark mode section
- refactor Dark mode page

UI library:
- bring in intellisense, linting and formatting in all `theme` objects, using `createTheme()` proxy function
- fix and upgrade all deprecated tests by upgrading `vitest` to latest
- cleanup dependencies (of all kind)

Storybook:
- upgrade to storybook 8
- light/dark mode widget toggle
- remove next dependency examples

CLI:
- create `create-flowbite-react` CLI package (https://www.npmjs.com/package/create-flowbite-react)

### Result

Docs - Quickstart

https://github.com/themesberg/flowbite-react/assets/41998826/986affaa-dd86-45c0-8c8b-c1067700d070

Docs - Integration Guides - CLI section

Screenshot 2024-03-20 at 10 50 24

Docs - code preview

https://github.com/themesberg/flowbite-react/assets/41998826/02c4e3da-a533-49ab-9c44-ce26a514f3b3

https://github.com/themesberg/flowbite-react/assets/41998826/3c65890c-d49f-4bcb-8ee9-34e20f05d7ce

Storybook - light/dark mode toggle

https://github.com/themesberg/flowbite-react/assets/41998826/b4ef547f-d9ff-4c1e-b3f5-5209d6159d7d

CLI

https://github.com/themesberg/flowbite-react/assets/41998826/ebafe22a-ee11-46c1-9f40-a479b6176a2e

Screenshot 2024-03-20 at 11 05 06

### CODE REVIEW

**Comment by dhavalveera** [comment]
> ### Summary
> 
> Since there is a lot of confusion regarding which files belong to docs, and which belong to the UI library, as well as which files are simply for code quality and which not, we should have a split bringing separation of concerns that isolates each app/package into their own namespace, while still allowing the flexibility of re-usage of one another (eg: UI lib being used in docs namespace).
> 
> To achieve this, the answer is **monorepo**.
> ### Structure
> 
>     * [x]  apps
>       
>       * [x]  storybook
>       * [x]  web
> 
>     * [x]  packages
>       
>       * [ ]  cli
>       * [x]  ui
> 
> 
> ### Stack
> 
> Task runner: `Bun` Package manager: `Bun` Lint: `ESLint` Format: `Prettier` Test: `Vitest`
> ### Changes
> ### Issues
> ### API changes

would love to learn more about this monorepo!.

**Comment by SutuSebastian** [comment]
@coderabbitai pause

**Comment by SutuSebastian** [comment]
@coderabbitai resume

**Review by rluders — APPROVED** [review]
All right. This OR is waaaay too big to be reviewed properly. My browser is struggling to pass through all the changes. However, I've been following the changes for ~2 months, and today I tested it locally. I didn't notice any immediate problem. Nothing seems to be broken at first glance, and I think that the benefits of getting it merged are bigger than the risks related to it. So... I'm approving this PR.

**Comment by zoltanszogyenyi** [comment]
This is an amazing PR @SutuSebastian. Good job!

**Pull request merged**
