### PR TITLE
Feat/lists component

### PR DESCRIPTION
**Pull request by paghar**
- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

### CODE REVIEW

**Comment by SutuSebastian** [comment]
These changes will only work in the versions before https://github.com/themesberg/flowbite-react/pull/994, but since the HEAD of `main` is not having `useTheme()` anymore, we need to go back in time, merge this in a separate branch and publish it, only after that bring in the merge updated according to the new theme engine that supports RSC and make the `List` RSC compatible.

CC @paghar @rluders

**Comment by paghar** [comment]
> These changes will only work in the versions before #994, but since the HEAD of `main` is not having `useTheme()` anymore, we need to go back in time, merge this in a separate branch and publish it, only after that bring in the merge updated according to the new theme engine that supports RSC and make the `List` RSC compatible.
> 
> CC @paghar @rluders

I understand that, thanks @SutuSebastian ,
I have updated this branch and pulled changes from main, resolved the conflicts and updated the theme engine for list component...
is that necessary to do all these stuff in a separate branch? @rluders @SutuSebastian

**Comment by SutuSebastian** [comment]
@paghar u're welcome!

Its kind of a direct dependency in case of wanting to publish the package now, because u would have to keep it as-is with "useTheme" hook and deploy it from a separate branch (idk if this is possible, @rluders may know better).

Case 1: deploy it for version 0.6xx
- needs a branch starting from the last 0.6xx version now on NPM, then have that branch published, then switch to main branch and apply the docs with the new docs engine (needs a bit more work)

Case 2: make it work with 'main' branch with the new docs engine, and it will be deployed to NPM on version 0.7 probably

@rluders @MateoWartelle @nigellima @tulup-conner thoughts?

**Comment by rluders** [comment]
@SutuSebastian TBH, I think that it is fine to release the 0.7.0 now and then work on the documentation improvements that are missing. I guess that also, most changes that we will include are not breaking changes, so the chances for us to leave the `0.7.0` would be pretty low. There is, however, one big change that we need to do, which is probably to `0.8.0` which is to change the "Color API" for the components. It is a little bit messy and I would like to see it as a pretty standard name convention and a unified interface.

So, long story short, I'm fine to release the `0.7.0` in the current state. I'll also find some time to improve the documentation parts that are missing this Friday. If someone could please address one of the issues for the missing parts for RSC and Docs it would be easier to track it. (I'll only have some free time on Friday)

And yes, if we want to release the `0.6.*` with the changes we will need to create a branch, cherry-pick the commits that we want to release, make sure to resolve any conflicts, and then do a release from that branch. TBH, I don't think that it is worth the job if the only piece missing for `0.7.0` release is just the documentation and some smaller non-breaking changes.

**Comment by SutuSebastian** [comment]
@rluders In that case, all forces ahead with the `0.7.0` release!

**Comment by paghar** [comment]
> @SutuSebastian TBH, I think that it is fine to release the 0.7.0 now and then work on the documentation improvements that are missing. I guess that also, most changes that we will include are not breaking changes, so the chances for us to leave the `0.7.0` would be pretty low. There is, however, one big change that we need to do, which is probably to `0.8.0` which is to change the "Color API" for the components. It is a little bit messy and I would like to see it as a pretty standard name convention and a unified interface.
> 
> So, long story short, I'm fine to release the `0.7.0` in the current state. I'll also find some time to improve the documentation parts that are missing this Friday. If someone could please address one of the issues for the missing parts for RSC and Docs it would be easier to track it. (I'll only have some free time on Friday)
> 
> And yes, if we want to release the `0.6.*` with the changes we will need to create a branch, cherry-pick the commits that we want to release, make sure to resolve any conflicts, and then do a release from that branch. TBH, I don't think that it is worth the job if the only piece missing for `0.7.0` release is just the documentation and some smaller non-breaking changes.
> 
> And now I just start to repeat myself. LOL

Sorry, I did not understand clearly what should I do!
I would be thankful if you help me to merging this feature ...
@rluders @SutuSebastian 🙏

**Comment by SutuSebastian** [comment]
@paghar there is a new docs engine in place now, not sure if u had time to take a look around how a doc page is built now and also how sidebar items get updated.

It would be much easier if u could take as an example `alert.root.tsx` and see how everything works in the docs page.
I also could just cherry pick the changes from this PR, and continue the work, after which u can review it. It would be more like a first-time-do-it example.

We can even sync on Discord and I can show u in more details how things work today.

**Comment by paghar** [comment]
> @paghar there is a new docs engine in place now, not sure if u had time to take a look around how a doc page is built now and also how sidebar items get updated.
> 
> It would be much easier if u could take as an example `alert.root.tsx` and see how everything works in the docs page. I also could just cherry pick the changes from this PR, and continue the work, after which u can review it. It would be more like a first-time-do-it example.
> 
> We can even sync on Discord and I can show u in more details how things work today.

Sure, Can I have your discord ID?

**Comment by SutuSebastian** [comment]
> > @paghar there is a new docs engine in place now, not sure if u had time to take a look around how a doc page is built now and also how sidebar items get updated.
> 
> > 
> 
> > It would be much easier if u could take as an example `alert.root.tsx` and see how everything works in the docs page. I also could just cherry pick the changes from this PR, and continue the work, after which u can review it. It would be more like a first-time-do-it example.
> 
> > 
> 
> > We can even sync on Discord and I can show u in more details how things work today.
> 
> 
> 
> Sure, Can I have your discord ID?

sebastian.sutu

**Pull request closed without merging**
