### PR TITLE
docs: improve content of docs and components for #767

### PR DESCRIPTION
**Pull request by zoltanszogyenyi**
## Description

This PR improves the documentation, copywriting and options of all of the component docs.

Fixes https://github.com/themesberg/flowbite-react/issues/767

## Type of change

Please delete options that are not relevant.

- [x] This change contains documentation update

## Breaking changes

No breaking changes.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist:

List of pages:

- [x] Accordion
- [x] Alerts
- [x] Avatar
- [x] Badge
- [x] Breadcrumb
- [x] Buttons
- [x] Button group
- [x] Cards
- [x] Carousel
- [x] Dropdown
- [x] Footer
- [x] Forms
- [x] List group
- [x] Modal
- [x] Navbar
- [x] Pagination
- [x] Progress
- [x] Rating 
- [x] Sidebar
- [x] Spinner
- [x] Table
- [x] Tabs (~~need help to pass state to last component `.mdx` file @tulup-conner~~ fixed with props to mdx)
- [x] Timeline
- [x] Toast
- [x] Tooltip

General:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by tulup-conner** [comment]
@zoltanszogyenyi Once you're ready for me to review this set "Ready for review" above and make me a Reviewer

**Comment by tulup-conner** [comment]
@zoltanszogyenyi BTW - Can you do me a favor and delete the `CNAME` file in this PR? It was only used for Github Pages

**Comment by zoltanszogyenyi** [comment]
Hey @tulup-conner,

Almost done with the docs - not sure how to pass state from `tabs/index.tsx` to `tabs.mdx`.

Here's the component that throws errors:

```
<CodePreview
code={`const Tabs: FC = () => {
const [activeTab, setActiveTab] = useState<number>(0);
const tabsRef = useRef<TabsRef>(null);

return (

<>
<Tabs.Group
aria-label="Default tabs"
style="default"
ref={tabsRef}
onActiveTabChange={tab => setActiveTab(tab)} >
<Tabs.Item active title="Profile">
Profile content
</Tabs.Item>
<Tabs.Item title="Dashboard">Dashboard content</Tabs.Item>
<Tabs.Item title="Settings">Settings content</Tabs.Item>
<Tabs.Item title="Contacts">Contacts content</Tabs.Item>
</Tabs.Group>
<div>Active tab: {activeTab}</div>
<Button.Group>
<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(0)}>
Profile
</Button>
<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(1)}>
Dashboard
</Button>
<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(2)}>
Settings
</Button>
<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(3)}>
Contacts
</Button>
</Button.Group>
</>
);
};`}
title="Set active tab programmatically" >
<Tabs.Group
aria-label="Default tabs"
style="default"
ref={tabsRef}
onActiveTabChange={(tab: SetStateAction<number>) => setActiveTab(tab)} >
<Tabs.Item active title="Profile">
Profile content
</Tabs.Item>
<Tabs.Item title="Dashboard">Dashboard content</Tabs.Item>
<Tabs.Item title="Settings">Settings content</Tabs.Item>
<Tabs.Item title="Contacts">Contacts content</Tabs.Item>
</Tabs.Group>
<div>Active tab: {activeTab}</div>
<Button.Group>
<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(0)}>
Profile
</Button>
<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(1)}>
Dashboard
</Button>
<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(2)}>
Settings
</Button>
<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(3)}>
Contacts
</Button>
</Button.Group>
</CodePreview>
```

Same thing for the Pagination, Forms, and Modal components. There I still have to create the `mdx` file with content.

Otherwise I'm super close to finishing this off and then to move to create other PRs.

Would be great if you could show me a way at least for the Tabs page.

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
I managed to find a way to access them via the `props` variable directly from `.mdx` files - I will finish this today.

Found quite a few bugs along the way with components, already created one issue for the modal placement.

**Comment by zoltanszogyenyi** [comment]
Hey @tulup-conner,

I'm done with this PR - please review it and let's merge it asap so that the new content can be indexed.

There's lots to work on still, however, this is a pretty good start for creating better documentation and description for the components. All of the content is unique and hand-written so search engines will definitely pick up on this.

Cheers,
Zoltan

**Comment by tulup-conner** [comment]
@zoltanszogyenyi You need to rebase, then if it looks good you're safe to merge.

**Comment by zoltanszogyenyi** [comment]
@tulup-conner it's up to date with main now

**Pull request merged**
