### PR TITLE
feat(button.tsx): Added as prop to button component

### LINKED ISSUE #655: `Button` with `as={Link}`
**Is your feature request related to a problem? Please describe.**
I would like to be able to change the `Button` root component to use `Link` from `react-router-dom`

**Describe the solution you'd like**
Implement `as={}` property to support `Link` or `a` or `button`.

**Describe alternatives you've considered**
None

**Additional context**
Check this: https://codesandbox.io/s/example-for-button-forked-d51fyi?from-embed

### PR DESCRIPTION
**Pull request by nigellima**
## Description

Fixes #655

As @tulup-conner commented [here](https://github.com/themesberg/flowbite-react/pull/681#issuecomment-1579567168), I decided to create a new PR with the simplest solution based on the SidebarItem component.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change contains documentation update

## Breaking changes

No breaking changes

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rluders — CHANGES_REQUESTED** [review]
@nigellima looks nice. I noticed one small detail... in the documentation, for the code sample that you created, when I'm hovering the button that is using `span` it doesn't actually change the mouse pointer. I think that would be nice to have it.

**Comment by nigellima** [comment]
@rluders something failed in the CI Build workflow which I think is not related to my previous commit. Couldnt find a way to re-run either

**Review by rluders — APPROVED** [review]
Thank you @nigellima.

**Comment by tulup-conner** [comment]
This is excellent @nigellima thank you again

**Comment by Rubens10010** [comment]
I noticed `href` prop is not working as intended for nextjs Link component. It should append basePath as in Navbar.Link component but it doesn't.

**Comment by rluders** [comment]
@Rubens10010 if you don't open an issue it will be lost.

**Comment by tulup-conner** [comment]
@Rubens10010 Can you elaborate on what you mean by that about basePath?

**Pull request merged**
