### PR TITLE
fix(components/accordion): allow opened panel to be closed

### LINKED ISSUE #618: `<Accordion.Content>`s can't be closed once expanded
**Describe the bug**
You can't click the close button on the active (currently open) `<Accordion.Content>`.

**Expected behavior**
You should be able to also close the active item which will just leave the `<Accordion>` with all items collapsed.

### PR DESCRIPTION
**Pull request by mufasubhai**
## Description

setOpen function didn't allow for current value to be removed if the item being clicked on was already open. As a result, it was not possible to close an accordion drawer by toggling it. 

Added toggleOpen function to set out of range value for open if the current target was already open. 

Fixes #618 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

Please document the breaking changes if suitable.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A: tested functionality locally. 
- [x] Test B: ran test suite to confirm no breaking changes. 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by rluders — CHANGES_REQUESTED** [review]
@mufasubhai seems to work. I would like however to see some unit tests for it. :)

**Comment by rluders** [comment]
> Sounds good @rluders. I'll add some over the next couple days. Thanks for the feedback!

still missing the unit tests that you promised me.  💔 🤣

**Comment by mufasubhai** [comment]
Oh jeez. It's been a while, hasn't it? My apologies. I'll try and update these today or tomorrow!

**Comment by mufasubhai** [comment]
recreated under pull request 705 (re-synced fork prior to creating the new PR.) Let me know if there are any other changes you need made. Sorry for the delay!

https://github.com/themesberg/flowbite-react/pull/705

**Pull request closed without merging**
