### PR TITLE
feat(avatar): adds color prop and test case for it

### LINKED ISSUE #409: Support colors in Avatar component
Avatar component has color property, but it doesn't work. Any color that is passed doesn't change anything.
IMO, it should have the following colours:
- dark
- failure
- gray/info/light
- purple
- success
- warning
- pink

Gray, info and light, if all added, should have different tones, to distinguish them.

I've tried to implemented and almost got it to work, so I think whoever picks this should:
- Change `default.ts` and add color styling on 'avatar' key value (see snippets below)
- `Avatar.tsx` must extends from Omit instead of PropsWithChildren and have 'color' argument passed. It should have another prop called `color` with a custom interface that explicit tells the colour options. Add `theme.color[color]` at least on the placeholder HTML element.
- Add the custom interface from previous step into `FlowbiteTheme.ts` on avatar key.

### PR DESCRIPTION
**Pull request by sldk-yuri**
1. Adds color property to Avatar component to change image ring color. Works only if border property is true. 
2. Adds 'color' test case to the Avatar`s Theme test case

#409

## Description

Implements avatar component enhancement introduced by @tiagossa1 The component has ability to change image ring color via prop `color` if `bordered` prop is true.

Fixes #409

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

`'should use custom colors'` case was added to `'Components / Avatar'` -> `'Theme'` in Avatar.spec.tsx 
Storybook story works correct without any updates.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rluders** [comment]
@sldk-yuri is it good to review? :)

**Comment by sldk-yuri** [comment]
@rluders yes, it's. Take an additional look at default color pallete for avatar component `lib/default.ts` from line 70 to 80, please. Probably we may change/update it with new colors. Thank you.

**Comment by rluders** [comment]
I think this is fine as it is... AFAIK, people still can extend the colors as their like, and add some custom colors to their own theme. Thank you, I'm accepting this PR.

**Comment by sldk-yuri** [comment]
@rluders Thank you.

**Pull request merged**
