### PR TITLE
Removes the default margin-left on Navbar.Toggle

### PR DESCRIPTION
**Pull request by flov**
## Description

This should be optional as a prop in the component or just wrap the toggle in a div.
Having this as a default makes it difficult to
Change it.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change contains documentation update

## Breaking changes

Please document the breaking changes if suitable.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rluders** [comment]
@flov I agree with you on this one. Could you please also fix the documentation and storybook examples by wrapping them with something with `ml-3` class?

**Review by rluders — CHANGES_REQUESTED** [review]
@flov I agree with you on this one. Could you please also fix the documentation and storybook examples by wrapping them with something with `ml-3` class?

**Comment by flov** [comment]
Sure, just fixed the stories for Navbar. Not sure about the docs, what would need to be changed there?

**Comment by rluders** [comment]
> Sure, just fixed the stories for Navbar. Not sure about the docs, what would need to be changed there?

The changes looks good. Thanks.

**Comment by flov** [comment]
Cool :) when can I expect it to appear in the newest version?

**Comment by rluders** [comment]
Friday! :)

**Pull request merged**
