### PR TITLE
docs(general): improve styles and meta data

### LINKED ISSUE #863: Documentation styles
## Steps to reproduce

1. Go to https://flowbite-react.com/

## Current behavior

There are some style differences that need to be adjusted - I will also set up the favicon because Google doesn't pick it up and add a custom OG image.

## Expected behavior

Improve these.

### PR DESCRIPTION
**Pull request by zoltanszogyenyi**
This PR fixed #863 by improving styles for the documentation and meta data.

### CODE REVIEW

**Review by tulup-conner — APPROVED** [review]
LGTM, there's a few files I think you added that aren't actually referenced but that doesn't really matter at all

**Comment by tulup-conner** [comment]
Also, you called this branch "863" BTW - it should have a semantic name of some kind or just anything other than "863" haha

**Comment by zoltanszogyenyi** [comment]
Hey @tulup-conner,

Haha, sorry for the branch name - added it to be the same as the issue number I guess.

Do you want to merge it?

Cheers,
Zoltan

**Comment by rluders** [comment]
image

**Pull request merged**
