### PR TITLE
fix(component): add forwardRef to TextInput

### LINKED ISSUE #211: Cannot forward ref to TextInput component
**Describe the bug**
I am trying to use the [headlessui combobox component](https://headlessui.dev/react/combobox), which allows you to use an `as` prop to render a differerent input. If I use flowbites TextInput this does not work, even with a forwardRef. 

**To Reproduce**
I have created a sandbox demonstrating the issue and a solution.

https://codesandbox.io/s/flowbite-input-forward-ref-pvtg1m

**Expected behavior**
Should forward the ref to the inner input element.

### PR DESCRIPTION
**Pull request by davemooreuws**
Fixes #211 

## Breaking changes
None

### CODE REVIEW

**Comment by tulup-conner** [comment]
Sweet, I just wrote a test case and checked that it works. I'm not sure if I can add that to the PR or if we'll just have to add it later. Here's a gist of it: https://gist.github.com/tulup-conner/eaecb353448d98f04b5657cee903b139

Thank you for this! I think we'll want to do it for all of the form input components at some point, then.

**Review by tulup-conner — APPROVED** [review]

**Comment by davemooreuws** [comment]
@tulup-conner Yep, we will want to add it to all of them. 
If you are marked as a maintainer, I believe you can add commits, the test looks great to me.

**Comment by tulup-conner** [comment]
I tried but it looks like I don't have the right permissions, so I notified the maintainers :)

**Review by rluders — CHANGES_REQUESTED** [review]
Hi, @davemooreuws. First at all, thanks for the PR. I'm getting an issue to run your code. Could you please check it?

```
WARNING in src/lib/components/FormControls/TextInput.tsx
  Line 1:1:  Imports "ComponentProps", "FC" and "ReactNode" are only used as types  @typescript-eslint/consistent-type-imports

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.72.0 compiled with 2 warnings in 11133 ms
ERROR in src/lib/components/FormControls/FileInput.tsx:10:11
TS2322: Type '{ type: "file"; value?: string | number | readonly string[] | undefined; checked?: boolean | undefined; multiple?: boolean | undefined; dir?: string | undefined; form?: string | undefined; slot?: string | undefined; ... 286 more ...; className: string; }' is not assignable to type 'RefAttributes<HTMLInputElement>'.
  Types of property 'ref' are incompatible.
    Type 'LegacyRef<HTMLInputElement> | undefined' is not assignable to type 'Ref<HTMLInputElement> | undefined'.
      Type 'string' is not assignable to type 'Ref<HTMLInputElement> | undefined'.
     8 |
     9 | export const FileInput: FC<FileInputProps> = ({ className, ...props }) => {
  > 10 |   return <TextInput className={classNames('!p-0', className)} {...props} type="file" />;
       |           ^^^^^^^^^
    11 | };
    12 |

ERROR in src/lib/components/FormControls/TextInput.stories.tsx:11:52
TS2322: Type '{ ref?: LegacyRef<HTMLInputElement> | undefined; key?: Key | null | undefined; accept?: string | undefined; alt?: string | undefined; autoComplete?: string | undefined; ... 288 more ...; icon?: FC<...> | undefined; }' is not assignable to type 'RefAttributes<HTMLInputElement>'.
  Types of property 'ref' are incompatible.
    Type 'LegacyRef<HTMLInputElement> | undefined' is not assignable to type 'Ref<HTMLInputElement> | undefined'.
     9 | } as Meta;
    10 |
  > 11 | const Template: Story<TextInputProps> = (args) => <TextInput {...args} />;
       |                                                    ^^^^^^^^^
    12 |
    13 | export const Default = Template.bind({});
    14 | Default.storyName = 'Text input';
```

**Comment by davemooreuws** [comment]
> Hi, @davemooreuws. First at all, thanks for the PR. I'm getting an issue to run your code. Could you please check it?
> 
> ```
> WARNING in src/lib/components/FormControls/TextInput.tsx
>   Line 1:1:  Imports "ComponentProps", "FC" and "ReactNode" are only used as types  @typescript-eslint/consistent-type-imports
> 
> 1 warning has detailed information that is not shown.
> Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
> 
> webpack 5.72.0 compiled with 2 warnings in 11133 ms
> ERROR in src/lib/components/FormControls/FileInput.tsx:10:11
> TS2322: Type '{ type: "file"; value?: string | number | readonly string[] | undefined; checked?: boolean | undefined; multiple?: boolean | undefined; dir?: string | undefined; form?: string | undefined; slot?: string | undefined; ... 286 more ...; className: string; }' is not assignable to type 'RefAttributes<HTMLInputElement>'.
>   Types of property 'ref' are incompatible.
>     Type 'LegacyRef<HTMLInputElement> | undefined' is not assignable to type 'Ref<HTMLInputElement> | undefined'.
>       Type 'string' is not assignable to type 'Ref<HTMLInputElement> | undefined'.
>      8 |
>      9 | export const FileInput: FC<FileInputProps> = ({ className, ...props }) => {
>   > 10 |   return <TextInput className={classNames('!p-0', className)} {...props} type="file" />;
>        |           ^^^^^^^^^
>     11 | };
>     12 |
> 
> ERROR in src/lib/components/FormControls/TextInput.stories.tsx:11:52
> TS2322: Type '{ ref?: LegacyRef<HTMLInputElement> | undefined; key?: Key | null | undefined; accept?: string | undefined; alt?: string | undefined; autoComplete?: string | undefined; ... 288 more ...; icon?: FC<...> | undefined; }' is not assignable to type 'RefAttributes<HTMLInputElement>'.
>   Types of property 'ref' are incompatible.
>     Type 'LegacyRef<HTMLInputElement> | undefined' is not assignable to type 'Ref<HTMLInputElement> | undefined'.
>      9 | } as Meta;
>     10 |
>   > 11 | const Template: Story<TextInputProps> = (args) => <TextInput {...args} />;
>        |                                                    ^^^^^^^^^
>     12 |
>     13 | export const Default = Template.bind({});
>     14 | Default.storyName = 'Text input';
> ```

Should all be good now, had to omit to old ref type.

**Review by rluders — APPROVED** [review]

**Pull request merged**
