### PR TITLE
Fix: listItem disabled property

### PR DESCRIPTION
**Pull request by paghar**
- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

### CODE REVIEW

**Comment by paghar** [comment]
Seems to be useless in the whole project!

**Comment by SutuSebastian** [comment]
@rluders @tulup-conner @MateoWartelle Do we plan to actually make it non-useless? 😄

**Comment by rluders** [comment]
> @rluders @tulup-conner @MateoWartelle Do we plan to actually make it non-useless? 😄

Let's apply it properly instead of removing it:
https://flowbite.com/docs/components/list-group/#list-group-with-buttons

**Comment by paghar** [comment]
@rluders @SutuSebastian It is good to go now...

**Review by rluders — APPROVED** [review]

**Pull request merged**
