### PR TITLE
redwood-js.mdx update command to add flowbite-react into web workspace

### PR DESCRIPTION
**Pull request by ganesshkumar**
updating command to add flowbite-react to web workspace

- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

## Summary by CodeRabbit

- **Documentation**
	- Updated the installation guide for `flowbite-react` in RedwoodJS projects to ensure correct workspace addition.

### CODE REVIEW

**Comment by rluders** [comment]
Forgive my ignorance here @iamargentum... does it need to use the workspace command or is it just recommended?

**Comment by iamargentum** [comment]
not exactly sure why i am tagged here
could you please elaborate @rluders ?
will be happy to help :)

**Comment by SutuSebastian** [comment]
> Forgive my ignorance here @iamargentum... does it need to use the workspace command or is it just recommended? 

To give a bit of context, redwood uses yarn workspaces (monorepo setup) and the PR is actually correct because we need to install `flowbite-react` in the frontend/web folder instead at the root level of the monorepo.

**Comment by rluders** [comment]
> not exactly sure why i am tagged here
> 
> could you please elaborate @rluders ?
> 
> will be happy to help :)

@iamargentum tagging going wrong. Actually it was to tag @ganesshkumar

**Comment by ganesshkumar** [comment]
@SutuSebastian  Thanks for adding the info.

Also running `yarn add flowbite-react` throws the following error. Either we have to pass `--ignore-workspace-root-check` or we need to add it only to the `web` workspace - which is what we want. 

`
>  yarn add flowbite-react          
yarn add v1.22.22
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

**Review by rluders — APPROVED** [review]

**Comment by rluders** [comment]
Thanks, @SutuSebastian and @ganesshkumar for the clarification.

**Pull request merged**
