### PR TITLE
feat: indicator Component

### PR DESCRIPTION
**Pull request by MateoWartelle**
- [X] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

Indicator component to match 
https://flowbite.com/docs/components/indicators/

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

### CODE REVIEW

**Comment by rluders** [comment]
This PR will also be required to update some other components. I can only remember the `Avatar` right now, but there are probably some others.

**Comment by MateoWartelle** [comment]
> This PR will also be required to update some other components. I can only remember the `Avatar` right now, but there are probably some others.

Yes I couldn't get it to work on this example : 

https://flowbite-react-l570u8y3f-themesberg.vercel.app/docs/components/indicators#status-indicator

**Comment by MateoWartelle** [comment]
> This PR will also be required to update some other components. I can only remember the `Avatar` right now, but there are probably some others.

What specifically?

**Comment by rluders** [comment]
> > This PR will also be required to update some other components. I can only remember the `Avatar` right now, but there are probably some others.
> 
> What specifically?

https://github.com/themesberg/flowbite-react/blob/1189d3d16981ba4405f450ddfd242df4d91576b9/src/components/Avatar/Avatar.tsx#L147

The `Avatar` component has an inner indicator that is used only for it. With the `Indicator` component, it would be nice to use it for the component or any other approach that I'm not considering here.

**Pull request closed without merging**
