### PR TITLE
refactor(footer): Adds the theme support to footer component 

### PR DESCRIPTION
**Pull request by mouracamila**
## Description

Rewrite the component footer to accept theme.

Fixes #177 

## Type of change

- [x]  Refactor: A code change that neither fixes a bug nor adds a feature 

## Breaking changes

- Some structural changes to the Footer layout.
- Removes the direct access to `className` to all footer components
- Adds the theme support to the component
```
  footer: {
    base: string;
    col: string;
    container: string;
    bgDark: string;
    groupLink: {
      base: string;
      link: {
        base: string;
        href: string;
      };
      col: string;
    };
    icon: {
      base: string;
      size: string;
    };
    title: {
      base: string;
    };
    divider: {
      base: string;
    };
    copyright: {
      base: string;
      href: string;
      span: string;
    };
    brand: {
      base: string;
      img: string;
      span: string;
    };
  };
```

## How Has This Been Tested?

- The page loaded and there was no error in the console

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by tulup-conner** [comment]
It looks like you rebased from the commitizen changes which havent been pulled yet so I will wait for you to rebase when that happens

**Comment by rluders** [comment]
This component is HUGE!!!

I did some small adjusts to the code, I hope you don't mind @mouracamila.
So we need to think in some way to improve it in the future, but right now, I can only say: Great job! :+1: 

> 1. The CI is failing for some freaking reason, I have no idea why. But I don't think that it is related to the PR itself, 'cause it also failed into `main`. It issue seems to be related to reach the yarn register.
> 2. Not sure why the Codecov is complaining about test reduction. If he keeps complain about it, I'll recommend to add some tests per `component` at the footer. We don't have to test all, but just the ones that have some if statement.

**Comment by mouracamila** [comment]
> This component is HUGE!!!
> 
> I did some small adjusts to the code, I hope you don't mind @mouracamila. So we need to think in some way to improve it in the future, but right now, I can only say: Great job! +1
> 
> > 1. The CI is failing for some freaking reason, I have no idea why. But I don't think that it is related to the PR itself, 'cause it also failed into `main`. It issue seems to be related to reach the yarn register.
> > 2. Not sure why the Codecov is complaining about test reduction. If he keeps complain about it, I'll recommend to add some tests per `component` at the footer. We don't have to test all, but just the ones that have some if statement.

Ok, @rluders no problem :)

**Comment by mouracamila** [comment]
@rluders , I just realized that there are some elements that are not covered by the test, I will fix that.

**Comment by mouracamila** [comment]
@rluders I finish it

**Review by rluders — CHANGES_REQUESTED** [review]

**Pull request merged**
