### PR TITLE
Fix/conditional rendering tabs item

### PR DESCRIPTION
**Pull request by paghar**
- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

### CODE REVIEW

**Comment by paghar** [comment]
@rluders Hi, should I rebase changes?

**Comment by rluders** [comment]
> @rluders Hi, should I rebase changes?

Yes. No merge should be added to PR :)

**Comment by paghar** [comment]
Sorry! I closed the pull request. can you please re-open it?
@rluders

**Comment by rluders** [comment]
@paghar I actually can't re-open it. Just create a new PR.

**Pull request closed without merging**
