### PR TITLE
docs: documentation page for FileInput Component

### PR DESCRIPTION
**Pull request by MateoWartelle**
- [X] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

documentation page for the FileInput Component to match Flowbite website

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

### CODE REVIEW

**Comment by rluders** [comment]
@MateoWartelle isn't the `FileInput` documented here already? https://flowbite-react-git-fork-mateowartelle-docs-fileinput-themesberg.vercel.app/docs/components/forms#file-upload

Anyway, I think that we could separate all the docs for the `forms` components like the standard flowbite library does:

image

WDYT? @zoltanszogyenyi what would be the SEO impact here? Do we need to keep some redirects?

**Comment by zoltanszogyenyi** [comment]
@rluders the SEO impact is good because people also search for "file input", "search input" and so on. It shouldn't affect the content on the forms page, it's okay to have some duplicates especially if the content is different (the paragraphs). Whatever is on flowbite.com is already SEO proof:

General forms page:

https://flowbite.com/docs/components/forms/

Standalone input pages:

https://flowbite.com/docs/forms/input-field/
https://flowbite.com/docs/forms/file-input/
https://flowbite.com/docs/forms/search-input/

Cheers,
Zoltan

**Comment by rluders** [comment]
@MateoWartelle I know that it is probably a little bit "out of scope" for this PR, but since we moved the FileInput component to `forms/`... Do you mind making the same change for all other form-components?

**Comment by MateoWartelle** [comment]
> @MateoWartelle I know that it is probably a little bit "out of scope" for this PR, but since we moved the FileInput component to `forms/`... Do you mind making the same change for all other form-components?

Yes I think that is best.

**Comment by SutuSebastian** [comment]
maybe we should bring this back to life, but with the new docs engine changes. The code here can be just for parts-and-pieces to import into the `main` branch, one form component at a time 🤔

**Pull request closed without merging**
