### PR TITLE
WIP: Update Dropdown and Floating components

### LINKED ISSUE #624: Allow customizing the button for dropdowns
The Dropdown component is very opinionated.

I suggest adding a customizable `<Dropdown.Trigger>` component that would be used to render the `<button>` element. The `label` prop should be removed from `<Dropdown>` and `arrowIcon` and `floatingArrow` moved to `<Dropdown.Trigger>`.

Also, I would assume that the `<Dropdown.Item>` components would then need to be wrapped to differentiate between the trigger and the items.

Here's example markup that would render a red button with a 3 vertical dots icon:

```jsx
<Dropdown>
  <Dropdown.Trigger className="bg-red-500" arrowIcon={false}>
    Show the dropdown
    <HiDotsVertical />
  </Dropdown.Trigger>
  <Dropdown.Items>
    <Dropdown.Item icon={HiOutlinePencil} onClick={openRatePlanEditDialogAndCloseMenu}>
      Edit
    </Dropdown.Item>
    <Dropdown.Item icon={HiOutlineTrash} className="text-red-700">
      Delete
    </Dropdown.Item>
  </Dropdown.Items>
</Dropdown>
```

Or maybe allow the dropdown to be triggered from any element, not just buttons. Someone might want to use an icon instead of a button. For that, we could add a `<Trigger.Button>` element that would render the button with the arrow icon, but any children of `<Dropdown.Trigger>` can instead be used as a trigger.

### PR DESCRIPTION
**Pull request by multiwebinc**
**WIP.**

Fixes #624 and possibly others

I basically wrote the Floating and Dropdown components again based on https://floating-ui.com/docs/popover and there are guaranteed to be errors somewhere. There are a few Typescript warnings as well that I wasn't able to figure out in case someone wants to take a look at it. The Tooltip component will likely need to be looked at as well since it uses Floating.

With this, you should be able to create a Dropdown like this:

```jsx
<Dropdown trigger="click">
  <Dropdown.Trigger>
    <Button>
      <span className="flex gap-10">
        Show the Dropdown
        <Dropdown.Icon />
      </span>
    </Button>
  </Dropdown.Trigger>
  <Dropdown.Items>
    <Dropdown.Header>
      <span className="block text-sm">Bonnie Green</span>
      <span className="block truncate text-sm font-medium">bonnie@flowbite.com</span>
    </Dropdown.Header>
    <Dropdown.Item onClick={() => console.log('1')}>
      <HiOutlinePencil />
      Edit
    </Dropdown.Item>
    <Dropdown.Divider />
    <Dropdown.Item className="text-red-700">
      <HiOutlineTrash />
      Delete
    </Dropdown.Item>
  </Dropdown.Items>
</Dropdown>
```

### CODE REVIEW

**Comment by multiwebinc** [comment]
I think this is about done except for unit tests and the tooltip is a bit too close to the trigger item in case someone wants to look at it in the meantime. Also, I **think** [`/helpers/floating.ts`](https://github.com/multiwebinc/flowbite-react/blob/main/src/lib/helpers/floating.ts) is no longer in use, so can probably be deleted.

**Comment by multiwebinc** [comment]
@rluders @tulup-conner Do you guys have any feedback on the direction of this PR? It's basically done except for a couple of unit tests that are not passing. Help would be appreciated on that.

**Comment by tulup-conner** [comment]
Yep, let me take a look at this locally and get back to you.

**Comment by tulup-conner** [comment]
Also, please move this to a separate branch with Commitizen semantic naming, e.g., `feat/declarative-dropdown`

**Comment by tulup-conner** [comment]
I cloned this and installed everything fresh at 1adefbcfadf68cc03ccf941c5663a14634e2bedb but it's broken for me. See attached. I also had to make the following changes to get the dev environment to start:

image

```
diff --git a/src/docs/pages/AvatarPage.tsx b/src/docs/pages/AvatarPage.tsx
index eac109c..face14f 100644
--- a/src/docs/pages/AvatarPage.tsx
+++ b/src/docs/pages/AvatarPage.tsx
@@ -213,8 +213,6 @@ const AvatarPage: FC = () => {
           label={
             <Avatar alt="User settings" img="https://flowbite.com/docs/images/people/profile-picture-5.jpg" rounded />
           }
-          arrowIcon={false}
-          inline
         >
           <Dropdown.Header>
             <span className="block text-sm">Bonnie Green</span>
diff --git a/src/docs/pages/CardPage.tsx b/src/docs/pages/CardPage.tsx
index 6184c80..a148dd0 100644
--- a/src/docs/pages/CardPage.tsx
+++ b/src/docs/pages/CardPage.tsx
@@ -108,7 +108,7 @@ const CardPage: FC = () => {
         <div className="max-w-sm">
           <Card>
             <div className="flex justify-end px-4 pt-4">
-              <Dropdown inline label="">
+              <Dropdown label="">
                 <Dropdown.Item>
                   <a
                     href="#"
diff --git a/src/docs/pages/DropdownPage.tsx b/src/docs/pages/DropdownPage.tsx
index fba0556..b97165d 100644
--- a/src/docs/pages/DropdownPage.tsx
+++ b/src/docs/pages/DropdownPage.tsx
@@ -48,7 +48,7 @@ const DropdownPage: FC = () => {
     {
       title: 'Inline dropdown',
       code: (
-        <Dropdown label="Dropdown" inline>
+        <Dropdown label="Dropdown">
           <Dropdown.Item>Dashboard</Dropdown.Item>
           <Dropdown.Item>Settings</Dropdown.Item>
           <Dropdown.Item>Earnings</Dropdown.Item>
diff --git a/src/docs/pages/NavbarPage.tsx b/src/docs/pages/NavbarPage.tsx
index 441a71e..aa3673d 100644
--- a/src/docs/pages/NavbarPage.tsx
+++ b/src/docs/pages/NavbarPage.tsx
@@ -65,8 +65,6 @@ const NavbarPage: FC = () => {
           </Navbar.Brand>
           <div className="flex md:order-2">
             <Dropdown
-              arrowIcon={false}
-              inline
               label={
                 <Avatar
                   alt="User settings"
diff --git a/src/lib/components/Dropdown/Dropdown.stories.tsx b/src/lib/components/Dropdown/Dropdown.stories.tsx
index 4b4808a..b79a516 100644
--- a/src/lib/components/Dropdown/Dropdown.stories.tsx
+++ b/src/lib/components/Dropdown/Dropdown.stories.tsx
@@ -61,7 +61,6 @@ WithHeader.args = {
 
 export const Inline = Template.bind({});
 Inline.args = {
-  inline: true,
   children: (
     <>
       <Dropdown.Item>Dashboard</Dropdown.Item>
diff --git a/src/lib/components/Floating/FloatingIcon.tsx b/src/lib/components/Floating/FloatingIcon.tsx
index 8e6fd41..13655de 100644
--- a/src/lib/components/Floating/FloatingIcon.tsx
+++ b/src/lib/components/Floating/FloatingIcon.tsx
@@ -1,7 +1,7 @@
-import { useTheme } from 'flowbite-react';
 import type { ComponentProps, FC } from 'react';
 import { useMemo } from 'react';
 import { HiOutlineChevronDown, HiOutlineChevronLeft, HiOutlineChevronRight, HiOutlineChevronUp } from 'react-icons/hi';
+import { useTheme } from '../Flowbite';
 import { useFloatingContext } from './FloatingContext';
 
 const icons: Record<string, FC<ComponentProps<'svg'>>> = {
@@ -19,5 +19,5 @@ export const FloatingIcon: FC = () => {
     return placement ? icons[placement] : HiOutlineChevronDown;
   }, [placement]);
 
-  return <>{Icon && <Icon className={theme.arrowIcon} />}</>;
+  return <>{Icon && <Icon className={theme.floating.arrow.base} />}</>;
 };
diff --git a/src/lib/components/Navbar/Navbar.stories.tsx b/src/lib/components/Navbar/Navbar.stories.tsx
index 1237489..278cbce 100644
--- a/src/lib/components/Navbar/Navbar.stories.tsx
+++ b/src/lib/components/Navbar/Navbar.stories.tsx
@@ -75,8 +75,6 @@ WithDropdown.args = {
       </Navbar.Brand>
       <div className="flex gap-3 md:order-2">
         <Dropdown
-          arrowIcon={false}
-          inline
           label={
             <Avatar alt="User settings" img="https://flowbite.com/docs/images/people/profile-picture-5.jpg" rounded />
           }
```

I can't really test these since none of them are rendering correctly for me, so do let me know if you can reproduce the problems I'm having here.

**Comment by multiwebinc** [comment]
> Also, please move this to a separate branch with Commitizen semantic naming, e.g., `feat/add-declarative-dropdown`

Sorry, but my git skills are not the best. Are you saying you want me to rename `main` to `feat/add-declarative-dropdown`?

**Comment by multiwebinc** [comment]
> I cloned this and installed everything fresh at [1adefbc](https://github.com/themesberg/flowbite-react/commit/1adefbcfadf68cc03ccf941c5663a14634e2bedb) but it's broken for me.

I only updated the component itself. To test it you would have to put that component on a page. Or let me know what I need to update to test it like you're doing.

**Comment by Blagochevsky** [comment]
@multiwebinc do you have an update on this?

**Comment by multiwebinc** [comment]
@Blagochevsky To be honest, I decided to switch the app I was working on to use Radix combined with Skeleton UI themes, so I haven't worked much at all with Flowbite. I think this PR is mostly done, but it just needs the failing tests to be fixed and storybook to be updated with the new syntax. Maybe someone could add the "help wanted" tag?

**Comment by rluders** [comment]
I think this one was basically done by #840

**Pull request closed without merging**
