### PR TITLE
Component stories

### PR DESCRIPTION
**Pull request by mouracamila**
add missing stories

### CODE REVIEW

**Comment by bacali95** [comment]
Hey @mouracamila, can I review this or it is still a work in progress?

**Comment by mouracamila** [comment]
> Hey @mouracamila, can I review this or it is still a work in progress?

Hi @bacali95   yes it is, I need to add more stories in other components, but if you want to review this part and then the other one (because maybe there's a lot left to review), I haven't any problem :)

**Review by rluders — APPROVED** [review]
Great job.

I'm missing the Sidebar story and the Dropdown component isn't working as expected in the stories. But... I don't see it as a problem right now. We can handle it in separated PR, 'cause this one already introduces a lot of improvements, doesn't break anything, and is already complex enough to be reviewed.

So, I would say: LGTM.

**Review by bacali95 — APPROVED** [review]
LGTM as well, great job @mouracamila

**Comment by mouracamila** [comment]
> LGTM as well, great job @mour

> LGTM as well, great job @mouracamila

Thanks :)

**Comment by mouracamila** [comment]
> Great job.
> 
> I'm missing the Sidebar story and the Dropdown component isn't working as expected in the stories. But... I don't see it as a problem right now. We can handle it in separated PR, 'cause this one already introduces a lot of improvements, doesn't break anything, and is already complex enough to be reviewed.
> 
> So, I would say: LGTM.
> 
> @bacali95 what do you think?

Thanks, @rluders, good points!
I'll open up issues with that, just for don't forget

**Comment by mouracamila** [comment]
> LGTM as well, great job @mouracamila

Thanks, @bacali95 :)

**Pull request merged**
