### PR TITLE
test(alert): css classes verification

### PR DESCRIPTION
**Pull request by benilyxdd**
- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.
Added tests to verify if the CSS classes are aligned with the standard of Flowbite

Reference related issues using `#` followed by the issue number.
#823

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

### CODE REVIEW

**Comment by tulup-conner** [comment]
Thanks for your contribution! I like the idea of this, but I would prefer to find a solution that scales to every component without writing hundreds of tests. I'm not really sure what that is yet - but I think this would be a great place to experiment with that.

**Comment by benilyxdd** [comment]
@tulup-conner 

> every component without writing hundreds of tests
Do you mean the tests should also test the other components like Accordion and Button instead of just Alert?

**Comment by rluders** [comment]
> Thanks for your contribution! I like the idea of this, but I would prefer to find a solution that scales to every component without writing hundreds of tests. I'm not really sure what that is yet - but I think this would be a great place to experiment with that.

This is going to be hard, TBH. I don't see any other way to do it automatically or without writing a lot of unit tests. Probably in this case simple approach, even than not perfect, would be better than nothing.

**Comment by tulup-conner** [comment]
Thanks for contributing, but I don't think we have any plans to implement something like this because it would be such a monumental task. Definitely check out one of the other open issues if you have some time and want to help out, it would be greatly appreciated :D

**Pull request closed without merging**
