### PR TITLE
Fix/remove unneccesary dependency array

### PR DESCRIPTION
**Pull request by paghar**
- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

### CODE REVIEW

**Comment by paghar** [comment]
@rluders Please take a look at this, thanks....

**Comment by SutuSebastian** [comment]
@paghar I wouldn't really call it "unnecessary" tho, It is there more for performance because we want to mount the listeners once, not every single render. One single downside that I can think of is the callback closure and possibly stale/outdated callback variables if they have from one execution to another, but here with this implementation, it is not the case.

**Comment by rluders** [comment]
Agreed with @SutuSebastian. I think that we don't need this. But, thanks anyway. :)

**Comment by paghar** [comment]
@rluders @SutuSebastian Thanks for the explanation, Is there any better solution to get rid of that warning?

**Comment by rluders** [comment]
@paghar in this case, I think that we can just ignore it.

**Comment by rluders** [comment]
@paghar I'll reopen the PR so, maybe you can just add the line to ignore the warning and it should be all.

**Comment by paghar** [comment]
> @paghar I'll reopen the PR so, maybe you can just add the line to ignore the warning and it should be all.

Thanks @rluders 🙏

**Comment by paghar** [comment]
Done @rluders,
Thank you...

**Comment by SutuSebastian** [comment]
> @rluders @SutuSebastian Thanks for the explanation, Is there any better solution to get rid of that warning?

U're most welcome! Sure, there is a solution, that is putting the callback `handleStorageChange` in the dependency array, but this means that I **have** to memoise the callback everywhere I use it, its a bummer 🙄.

**Pull request merged**
