### PR TITLE
Update Banner.tsx

### PR DESCRIPTION
**Pull request by nikcode9**
enhanced.

### CODE REVIEW

**Comment by rluders** [comment]
@nikcode9 can you give more details and explain the goals here?

**Comment by rluders** [comment]
@nikcode9 and what are the benefits here? 🤔 @nigellima @SutuSebastian

**Comment by SutuSebastian** [comment]
Using typescript and prop-types at the same time is redundand.

No typescript -> prop types
Typescript -> no prop types

Other than that, I dont see much value being added here, this is not even a library component, it is just used for the docs, no need for fancy JSDoc or display name IMO

**Comment by SutuSebastian** [comment]
Also, we lost all native "div" element prop types

**Comment by rluders** [comment]
Okay. So, as I was thinking this is a nope. Thanks anyway, @nikcode9.

**Pull request closed without merging**
