### PR TITLE
fix(datepiker): incorrect names of days of the week in the datepicker

### PR DESCRIPTION
**Pull request by paghar**
- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.
The weekdays index is based on the "currentDate" variable and it was representing the wrong value that is fixed now

Reference related issues using `#` followed by the issue number.
fixes: #960

### CODE REVIEW

**Comment by paghar** [comment]
@rluders What is codeCov? I did not understand the error reposts.

**Comment by rluders** [comment]
> @rluders What is codeCov? I did not understand the error reposts.

Don't worry about codecov... we introduced some new components that were missing some unit tests, it is not a problem with your PR.

**Comment by rluders** [comment]
@paghar looks good. May I also ask you to check the issue with the week start and to include it on this PR?

**Comment by paghar** [comment]
> @paghar looks good. May I also ask you to check the issue with the week start and to include it on this PR?

Thanks @rluders.
Sure, what is the problem with the week start?

**Comment by rluders** [comment]
> > @paghar looks good. May I also ask you to check the issue with the week start and to include it on this PR?
> 
> Thanks @rluders. Sure, what is the problem with the week start?

You can notice that the property that should set the start of the week isn't working it says:

```js
{
  "0": "Saturday",
  "1": "Sunday",
  "2": "Monday"
}
```

The example is using `2` and it isn't starting on Monday, as it should be.

**Comment by paghar** [comment]
> > > @paghar looks good. May I also ask you to check the issue with the week start and to include it on this PR?
> > 
> > 
> > Thanks @rluders. Sure, what is the problem with the week start?
> 
> You can notice that the property that should set the start of the week isn't working it says:
> 
> ```js
> {
>   "0": "Saturday",
>   "1": "Sunday",
>   "2": "Monday"
> }
> ```
> 
> The example is using `2` and it isn't starting on Monday, as it should be.

@rluders Done, please check...

**Comment by rluders** [comment]
@paghar looks good. Just one more thing, you merged the main to your PR, could you please revert the merge and rebase it instead?

**Comment by paghar** [comment]
@rluders Thanks. Sure, I did as the documentation said about merge and creating pull request...
Could you please give me the instructions to do that?
If It helps I can fix the documentation then...

**Comment by rluders** [comment]
@paghar sure. An easy way to do it would be to reset the last commit where you merge it using the command:

```sh
git reset --hard HEAD~1
```

Then, push force to update the PR. Finally, using the GitHub interface, update the branch with rebase, like this:
image

**Comment by paghar** [comment]
@rluders  So, is that OK now??

**Comment by rluders** [comment]
@paghar commits are fine, but I'm getting this:

image

It should be Friday, right?

**Comment by paghar** [comment]
> @paghar commits are fine, but I'm getting this:
> 
> image
> 
> It should be Friday, right?

sorry for that, I'll fix it now

**Comment by paghar** [comment]
@rluders That is OK now!

**Comment by rluders** [comment]
Looks good, @paghar. Thank you!

**Pull request merged**
