### PR TITLE
fix(ButtonGroup): dynamic generated button with group wasn't styled properly

### LINKED ISSUE #1269: Dynamically generated buttons within a button group are not properly styled.
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

```js
<div className='mb-4'>
  <ButtonGroup>
    <Button>Button 1</Button>
    <Button>Button 2</Button>
    <Button>Button 3</Button>
    <Button>Button 4</Button>
    <Button>Button 5</Button>
  </ButtonGroup>
</div>
<div className='mb-4'>
  <ButtonGroup>
    <Button>Button 1</Button>
    {[2, 3, 4].map(value => <Button key={value}>Button {value}</Button>)}
    <Button>Button 5</Button>
  </ButtonGroup>
</div>
```
Will have the following result:
Screenshot 2024-02-11 at 17 44 58

## Current behavior

On the second line in the provided screenshot (where there are dynamically generated buttons) the 3rd button has rounded borders on the right hand side while the 5th button doesn't have rounded borders on the right hand side.

## Expected behavior

On the second line in the provided screenshot (where there are dynamically generated buttons) the 3rd button shouldn't have any rounded borders while the 5th button should have rounded borders on the right hand side.

### PR DESCRIPTION
**Pull request by dhavalveera**
Dynamically generated buttons within a button group are not properly styled. 

fix #1269 

image

### CODE REVIEW

**Comment by dhavalveera** [comment]
Hello @SutuSebastian , Sorry to bother you, but can you please review this PR?

**Review by SutuSebastian — APPROVED** [review]
this is a quick fix, we need to find a way to target the `Button` component while recursively searching through children, and only inject props into the button, not all children components.

let's merge this until that "final" solution appears

**Comment by dhavalveera** [comment]
> this is a quick fix, we need to find a way to target the `Button` component while recursively searching through children, and only inject props into the button, not all children components.
> 
> let's merge this until that "final" solution appears

Yeah!. Let's find a proper solution for it

**Comment by dhavalveera** [comment]
@SutuSebastian - this codecov issue again

**Comment by chunkerchunker** [comment]
> > this is a quick fix, we need to find a way to target the `Button` component while recursively searching through children, and only inject props into the button, not all children components.
> > let's merge this until that "final" solution appears
> 
> Yeah!. Let's find a proper solution for it

Suggested fix in https://github.com/themesberg/flowbite-react/pull/1323

**Pull request merged**
