### PR TITLE
fix(progressbar): fix unclear label usage (#468)

### LINKED ISSUE #468: Progressbar not clear label usage
**Describe the bug**

The current way that we enable and change progressbar label isn't very clear:

flowbite-react com_storybook__path=_story_components-button--default-button args=outline_true;fullSized_true;color_purple (2)

For example, in the case of the screenshot:

- `labelPosition: "none" `
- `labelProgress: true`

What is the expected result here? Should it display the label or not? What does `none` mean for the position?

**To Reproduce**

[Check the storybook](https://flowbite-react.com/storybook/?path=/story/components-progress--default&args=labelPosition:none;labelProgress:true)

**Expected behavior**

I would like to have more flexible labeling for the progressbar. I think that we should have two labels:
- `textLabel`, which could handle any custom text.
- `progressLabel`, which would handle the percent number of the progress bar.

I also would like to play with both positions and enable/disable them.

**Screenshots**

N/A

**System information:**

N/A

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.3.5
- Type: CRA

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by revnandi**
## Description

Added separate props to display/hide Progressbar progress percentage and label, also the ability to position these labels inside/outside separately.

Fixes #468 
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change contains documentation update

## Breaking changes

"label" prop renamed to textLabel

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit test for the conditional rendering of labels

**Test Configuration**:

N/A

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rluders** [comment]
@revnandi correct me if I'm wrong, but this PR fixes #468. Right?

**Comment by revnandi** [comment]
Yes correct

**Comment by rluders** [comment]
I guess that just need to include some unit tests to cover the scenario, and it should be good to merge.

**Review by rluders — CHANGES_REQUESTED** [review]
It looks good, just need to run the prettier to fix some code style issues.

**Comment by revnandi** [comment]
> It looks good, just need to run the prettier to fix some code style issues.

Thanks, the formatting has ben fixed

**Comment by rluders** [comment]
@revnandi it seems that there is one piece of code that was introduced and wasn't tested. Could you provide some unit test for it?

**Comment by revnandi** [comment]
> @revnandi it seems that there is one piece of code that was introduced and wasn't tested. Could you provide some unit test for it?

should be 100% now

**Review by tulup-conner — APPROVED** [review]
Thank you for this~!

**Pull request merged**
