### PR TITLE
Fix/conditional rendering tabs items

### PR DESCRIPTION
**Pull request by paghar**
- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

### CODE REVIEW

**Comment by paghar** [comment]
@rluders I think that is OK now, please check.

**Comment by rluders** [comment]
@paghar I'll ask you to include some unit tests to cover the scenario that the PR fixes so that we can avoid future regressions.

**Comment by paghar** [comment]
@rluders Task completed. Please inform me if there are any additional tasks or requirements.

**Review by rluders — APPROVED** [review]

**Comment by rluders** [comment]
Thank you @paghar

**Pull request merged**
