### PR TITLE
feat(components/drawer): adds drawer component to the library (extends from #664)

### PR DESCRIPTION
**Pull request by xiaohuilam**
# Description

This PR extends from #664 (contributed by @areski, but outdated from main branch).
I contributed too less to TypeScript projects. if any piece flawing, Corrections and Questions are welcome here.

# Type of change
Please delete options that are not relevant.

- [ ] <strike>Bug fix (non-breaking change which fixes an issue)</strike>
- [x] New feature (non-breaking change which adds functionality)
- [ ] <strike>Breaking change (fix or feature that would cause existing functionality to not work as expected)</strike>
- [ ] <strike>This change contains documentation update</strike>

# Checklist:
- [x] My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x]  I have commented my code, particularly in hard-to-understand areas
- [x]  I have made corresponding changes to the documentation
- [x]  My changes generate no new warnings
- [x]  I have added tests that prove my fix is effective or that my feature works
- [x]  New and existing unit tests pass locally with my changes
- [x]  Any dependent changes have been merged and published in downstream modules
- [x]  I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rluders** [comment]
@xiaohuilam can you update the PR to use this template? https://github.com/themesberg/flowbite-react/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by rluders** [comment]
Another thing... don't merge the main branch, instead, rebase it.

**Comment by xiaohuilam** [comment]
@rluders Got it, I'm starting research to compliant your and the community's requests

**Comment by rluders** [comment]
@xiaohuilam I just converted it to a draft, just make it ready for review when it was ready to be reviewed. :)

**Comment by tulup-conner** [comment]
Hey @xiaohuilam are you still active on this at all? Let me know if you're not able to finish.

**Comment by xiaohuilam** [comment]
> Hey @xiaohuilam are you still active on this at all? Let me know if you're not able to finish.



> Hey @xiaohuilam are you still active on this at all? Let me know if you're not able to finish.

Sorry because I'm busy on other projects. Please drop this PR. In the future i will re-submit a PR which compliant requirements if I have time in Q1 2024 and this feature not merged.

**Comment by tulup-conner** [comment]
No worries! We are planning to make this happen soon so we can pick up where you left off!

**Pull request closed without merging**
